project:
  title: "Project 1 Statistical Computation"
  type: website
  output-dir: _site
  
website: 
  navbar: 
    left:
      - href: "index.html"
        text: Welcome
      - href: "Project_1_Statistical_computation.qmd"
        text: Prac Day One
      - href: "Lowess_Practical.qmd"
        text: Prac Day Two/Three
      - href: "Miguels_second_question.qmd"
        text: Prac Day Four



