---
title: "Project_1_Statistical_computation"
format: html
---

Question 1 

The rows that contain at least one NA value are as follows:
```{r}
#| echo: false
loop_length <- nrow(airquality)
df_na_rows <- data.frame()
df <- data.frame()
for (i in 1:loop_length) {
  row_vec <- airquality[i, ] 
  if (any(is.na(row_vec))) {
    df_na_rows <- rbind(df_na_rows, row_vec)
  }
  else{
    df <- rbind(df, row_vec)
  }
}
print(df_na_rows)

# there is a far more efficient way of doing this in one line 
# df <- na.omit(airquality)  

```


Question 2

The ozone and temperature metrics are as follows:
```{r}
#| echo: false

# Note use DF otherwise it results in some values of NA
avg_ozone <- mean(df$Ozone)
sd_ozone <- sd(df$Ozone)
min_ozone <- min(df$Ozone) 
max_ozone <- max(df$Ozone)

avg_temp <- mean(df$Temp)
sd_temp <- sd(df$Temp)
min_temp <- min(df$Temp) 
max_temp <- max(df$Temp)

final_weather_vec <- data.frame(
  Mean = c(avg_ozone, avg_temp),
  Stand_Dev = c(sd_ozone, sd_temp),
  Min = c(min_ozone, min_temp),
  Max = c(max_ozone, max_temp)
)

print(final_weather_vec)
  

```

Question 3 and Question 4


```{r}
#| echo: false
# Dist = Y, Speed = X
speed_df = cbind(1, cars$speed)
dist_df = matrix(cars$dist)

# Calculating the estimates using the formula ((X^TX)^-1X^TY)
beta_hat <- solve(t(speed_df) %*% speed_df) %*% t(speed_df) %*% dist_df
print("Values using matrix multiplication")
print(beta_hat)

# Calculating it using the built in R function
cars_reg = lm(cars$dist~cars$speed)
print("Values using LM method")
print(cars_reg)
```


Question 5 (Jake's additional question):

```{r}
#| echo: false
std_err_func = function(x, y, b_hat){
  
  residuals <- y - x %*% b_hat
  
  n <- length(y)
  p <- ncol(x)  # Number of predictors including intercept
  s <- sqrt(sum(residuals^2) / (n - p))

  # Compute standard errors
  var_beta <- s^2 * solve(t(x) %*% x)  # Variance-covariance matrix
  se_beta <- sqrt(diag(var_beta))  # Standard errors

  return (se_beta)
}
# std_err_func(speed_df, dist_df, beta_hat)

t_stat_func <- function(estimate, std_err){
  t_stat <- estimate/std_err
  return (t_stat)
}
# t_stat_func(beta_hat, std_err_func(speed_df, dist_df, beta_hat))

p_val_func <- function(t_stat){ 
  # 2 sided since the test is if beta hat is equal to 0
  deg_of_free = length(dist_df) - 2 # number of observations less number of parameters less 1 (n-p-1)
  p_value <- 2 * (1 - pt(abs(t_stat), deg_of_free))
  return (p_value)
}
# p_val_func(t_stat_func(beta_hat, std_err_func(speed_df, dist_df, beta_hat)))

reg_df = data.frame(
                    Estimate = beta_hat,
                    Standard_error = std_err_func(speed_df, dist_df, beta_hat),
                    T_stat = t_stat_func(beta_hat, std_err_func(speed_df, dist_df, beta_hat)),
                    P_value = p_val_func(t_stat_func(beta_hat, std_err_func(speed_df, dist_df, beta_hat)))
                    )
print(reg_df)
```